## Dracula PRO

foreground #F8F8F2
background #0B0D0F

# black
color0 #0B0D0F
color8 #504C67

# red
color1 #FF9580
color9 #FFAA99

# green
color2  #8AFF80
color10 #A2FF99

# yellow
color3  #FFFF80
color11 #FFFF99

# blue
color4  #9580FF
color12 #AA99FF

# magenta
color5  #FF80BF
color13 #FF99CC

# cyan
color6  #80FFEA
color14 #99FFEE

# white
color7  #F8F8F2
color15 #FFFFFF
