# Roc

[language-server.roc-ls]
command = "roc_language_server"

[[language]]
name = "roc"
scope = "source.roc"
injection-regex = "roc"
file-types = ["roc"]
shebangs = ["roc"]
comment-token = "#"
language-servers = ["roc-ls"]
auto-format = true
indent = { tab-width = 4, unit = " " }
grammar = "roc"
roots = []


[[grammar]]
name = "roc"
source = { git = "https://github.com/faldor20/tree-sitter-roc.git", rev = "6ea64b6434a45472bd87b0772fd84a017de0a557" }
